// Firebase options stub - temporarily disabled
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

/// Firebase stub class while Firebase is disabled
class FirebaseOptions {
  const FirebaseOptions({
    required this.apiKey,
    required this.appId,
    required this.messagingSenderId,
    required this.projectId,
    this.authDomain,
    this.storageBucket,
    this.iosBundleId,
  });

  final String apiKey;
  final String appId;
  final String messagingSenderId;
  final String projectId;
  final String? authDomain;
  final String? storageBucket;
  final String? iosBundleId;
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example file - you need to replace these with your actual Firebase project values
/// Generate your actual firebase_options.dart file using: flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Stub implementation while Firebase is disabled
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnYef9OHD0-kJOACbSNXgvY_N2yhpCHy8',
    appId: '1:601708044595:web:tocke',
    messagingSenderId: '601708044595',
    projectId: 'tocke-staffscanner',
    authDomain: 'tocke-staffscanner.firebaseapp.com',
    storageBucket: 'tocke-staffscanner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnYef9OHD0-kJOACbSNXgvY_N2yhpCHy8',
    appId: '1:601708044595:android:b659c9c0779ea5272b1e46',
    messagingSenderId: '601708044595',
    projectId: 'tocke-staffscanner',
    storageBucket: 'tocke-staffscanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkBfBBE1xxMn134sNPcww0V-FJRacjwP0',
    appId: '1:601708044595:ios:725af5e348b6ae7f2b1e46',
    messagingSenderId: '601708044595',
    projectId: 'tocke-staffscanner',
    storageBucket: 'tocke-staffscanner.firebasestorage.app',
    iosBundleId: 'cl.tocketicket.staffscanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkBfBBE1xxMn134sNPcww0V-FJRacjwP0',
    appId: '1:601708044595:ios:725af5e348b6ae7f2b1e46',
    messagingSenderId: '601708044595',
    projectId: 'tocke-staffscanner',
    storageBucket: 'tocke-staffscanner.firebasestorage.app',
    iosBundleId: 'cl.tocketicket.staffscanner',
  );
}
