// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example file - you need to replace these with your actual Firebase project values
/// Generate your actual firebase_options.dart file using: flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnYef9OHD0-kJOACbSNXgvY_N2yhpCHy8',
    appId: '1:601708044595:web:tocke',
    messagingSenderId: '601708044595',
    projectId: 'tocke-staffscanner',
    authDomain: 'tocke-staffscanner.firebaseapp.com',
    storageBucket: 'tocke-staffscanner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnYef9OHD0-kJOACbSNXgvY_N2yhpCHy8',
    appId: '1:601708044595:android:b659c9c0779ea5272b1e46',
    messagingSenderId: '601708044595',
    projectId: 'tocke-staffscanner',
    storageBucket: 'tocke-staffscanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkBfBBE1xxMn134sNPcww0V-FJRacjwP0',
    appId: '1:601708044595:ios:725af5e348b6ae7f2b1e46',
    messagingSenderId: '601708044595',
    projectId: 'tocke-staffscanner',
    storageBucket: 'tocke-staffscanner.firebasestorage.app',
    iosBundleId: 'cl.tocketicket.staffscanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkBfBBE1xxMn134sNPcww0V-FJRacjwP0',
    appId: '1:601708044595:ios:725af5e348b6ae7f2b1e46',
    messagingSenderId: '601708044595',
    projectId: 'tocke-staffscanner',
    storageBucket: 'tocke-staffscanner.firebasestorage.app',
    iosBundleId: 'cl.tocketicket.staffscanner',
  );
}
